{% set name = "dash_vega_components" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_vega_components-{{ version }}.tar.gz
  sha256: fbbecde007e19fd1d9e486af89844a8d0a372af9e122f6fc2f6a509355abf371

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dash[dev]>=2.0.0

test:
  imports:
    - dash_vega_components
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Dash component for Vega-Altair charts
  home: https://github.com/altair-viz/dash-vega-components
  dev_url: https://github.com/altair-viz/dash-vega-components
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - binste
